import type { GiftBundleDraft, GiftBundleDraftAsset } from './giftBundleTypes';

export const starterGiftDraftAssets: GiftBundleDraftAsset[] = [
  {
    id: 'gold-lock-icon',
    name: 'Gold Lock Icon',
    kind: 'icon',
    status: 'selected',
    rarity: 'premium',
    priceCredits: 15,
    tags: ['gold', 'security', 'ui'],
    previewLabel: '🔒',
  },
  {
    id: 'luxury-key-sticker',
    name: 'Luxury Key Sticker',
    kind: 'sticker',
    status: 'selected',
    rarity: 'rare',
    priceCredits: 25,
    tags: ['key', 'collectible', 'gold'],
    previewLabel: '🗝️',
  },
  {
    id: 'velvet-bow-gift',
    name: 'Velvet Bow Gift',
    kind: 'digital-gift',
    status: 'draft',
    rarity: 'common',
    priceCredits: 10,
    tags: ['bow', 'gift', 'soft'],
    previewLabel: '🎀',
  },
  {
    id: 'collector-card-cover',
    name: 'Collector Card Cover',
    kind: 'pack-cover',
    status: 'selected',
    rarity: 'limited',
    priceCredits: 0,
    tags: ['cover', 'card', 'pack'],
    previewLabel: '💳',
  },
  {
    id: 'gold-ui-card',
    name: 'Gold UI Essentials Card',
    kind: 'card',
    status: 'selected',
    rarity: 'premium',
    priceCredits: 35,
    tags: ['card', 'ui', 'gold'],
    previewLabel: '✨',
  },
];

export const starterGiftBundleDraft: GiftBundleDraft = {
  id: 'luxury-locks-set',
  name: 'Luxury Locks Set',
  subtitle: 'Gold UI essentials and collectible lock-themed gifts.',
  description: 'A starter bundle for grouping selected sticker, icon, gift and card drafts into one upload-ready platform pack.',
  theme: 'gold-essentials',
  selectedAssetIds: ['gold-lock-icon', 'luxury-key-sticker', 'collector-card-cover', 'gold-ui-card'],
  coverAssetId: 'collector-card-cover',
  priceCredits: 99,
  tags: ['luxury', 'locks', 'gold', 'starter-pack'],
  createdAt: '2026-05-27T00:00:00.000Z',
  updatedAt: '2026-05-27T00:00:00.000Z',
};
