export type DashboardModuleContractStage =
  | 'scaffold'
  | 'service-contract'
  | 'persistence'
  | 'policy'
  | 'payment-ready'
  | 'production-ready';

export type DashboardModuleServiceContract = {
  id: string;
  title: string;
  stage: DashboardModuleContractStage;
  serviceOwner: string;
  apiSurface: string[];
  persistence: string[];
  auditEvents: string[];
  policyGates: string[];
  paymentHooks: string[];
  launchBlockers: string[];
  relatedView?: string;
};

export function serviceContractKey(roleSurface: string, title: string) {
  return `${roleSurface.trim()}::${title.trim()}`;
}

const contract = (
  roleSurface: string,
  title: string,
  stage: DashboardModuleContractStage,
  serviceOwner: string,
  apiSurface: string[],
  persistence: string[],
  auditEvents: string[],
  policyGates: string[],
  paymentHooks: string[],
  launchBlockers: string[],
  relatedView?: string,
): DashboardModuleServiceContract => ({
  id: serviceContractKey(roleSurface, title),
  title,
  stage,
  serviceOwner,
  apiSurface,
  persistence,
  auditEvents,
  policyGates,
  paymentHooks,
  launchBlockers,
  relatedView,
});

export const dashboardModuleServiceContracts: Record<string, DashboardModuleServiceContract> = {
  [serviceContractKey('Sub Dashboard', 'Wallet')]: contract(
    'Sub Dashboard',
    'Wallet',
    'payment-ready',
    'Wallet and ledger services',
    ['GET /wallet', 'GET /wallet/ledger', 'POST /top-ups/intents', 'GET /top-ups/intents/:id/receipt', 'GET /top-ups/admin/provider-readiness'],
    ['WalletAccount', 'WalletTransaction', 'TopUpIntent', 'PointBalance'],
    ['wallet.viewed', 'wallet.topup_started', 'wallet.transaction_opened', 'topup.provider_webhook_verified'],
    ['authenticated sub', 'age and identity verified where required', 'chargeback risk check', 'signed provider callback before wallet credit'],
    ['top-up provider intent', 'receipt record', 'spend ledger allocation', 'idempotent provider webhook event'],
    ['live processor SDK calls and deployment-owned provider accounts'],
    'wallet',
  ),
  [serviceContractKey('Sub Dashboard', 'Locked Vault')]: contract(
    'Sub Dashboard',
    'Locked Vault',
    'policy',
    'Vault privacy service',
    ['GET /sub-vault/records', 'POST /sub-vault/share', 'PATCH /sub-vault/review/:id'],
    ['SubVaultRecord', 'SubVaultConsentGrant', 'SubVaultAudit'],
    ['vault.record_opened', 'vault.share_requested', 'vault.review_decision'],
    ['verified consent before sharing', 'review note required for decisions', 'revocation honored immediately'],
    ['none until paid access is explicitly enabled'],
    ['provider-backed encrypted storage', 'retention and deletion job'],
    'subVault',
  ),
  [serviceContractKey('Sub Dashboard', 'Contracts / Agreements')]: contract(
    'Sub Dashboard',
    'Contracts / Agreements',
    'policy',
    'Keeper agreement service',
    ['GET /keeper/agreements', 'POST /keeper/agreements', 'PATCH /keeper/agreements/:id/revoke'],
    ['KeeperAgreement', 'AgreementConsentSnapshot', 'AgreementAudit'],
    ['agreement.created', 'agreement.accepted', 'agreement.revoked'],
    ['explicit consent capture', 'expiry required', 'revocation path always visible'],
    ['keeper allowance billing link', 'agreement-linked receipt'],
    ['signed snapshot export', 'agreement template versioning'],
    'keeperAllowance',
  ),
  [serviceContractKey('Sub Dashboard', 'Redemption')]: contract(
    'Sub Dashboard',
    'Redemption',
    'service-contract',
    'Rewards and redemption service',
    ['GET /rewards/redemptions', 'POST /rewards/redemptions', 'GET /rewards/catalogue'],
    ['RewardCatalogueItem', 'RewardRedemption', 'PointLedgerEntry'],
    ['redemption.started', 'redemption.approved', 'redemption.fulfilled'],
    ['points balance check', 'cooldown and daily limit check', 'manual review for high-value rewards'],
    ['points burn ledger', 'paid reward receipt when applicable'],
    ['fraud scoring', 'fulfilment SLA rules'],
    'giftsGoals',
  ),
  [serviceContractKey('Mistress Dashboard', 'Phone / Voice')]: contract(
    'Mistress Dashboard',
    'Phone / Voice',
    'service-contract',
    'Bookings and call session service',
    ['GET /bookings/call-slots', 'POST /bookings/voice-session', 'PATCH /bookings/:id/extend'],
    ['Booking', 'CallSession', 'CallRateCard', 'SessionExtension'],
    ['voice.booking_created', 'voice.session_started', 'voice.session_extended'],
    ['host availability check', 'masked contact only', 'session timer enforcement'],
    ['pre-authorised minutes', 'extension charge', 'creator payout share'],
    ['telephony provider integration', 'failed-session refund policy'],
    'bookings',
  ),
  [serviceContractKey('Mistress Dashboard', 'Video Calls')]: contract(
    'Mistress Dashboard',
    'Video Calls',
    'service-contract',
    'Bookings and live session service',
    ['GET /bookings/video-slots', 'POST /bookings/video-session', 'POST /live/video-room-token'],
    ['Booking', 'VideoSession', 'RoomAccessToken', 'SessionExtension'],
    ['video.booking_created', 'video.room_opened', 'video.session_closed'],
    ['host and sub consent gate', 'room token expiry', 'recording disabled unless explicit policy allows'],
    ['pre-authorised session fee', 'extension charge', 'receipt and payout split'],
    ['video provider token service', 'session failure reconciliation'],
    'bookings',
  ),
  [serviceContractKey('Mistress Dashboard', 'PPV Content')]: contract(
    'Mistress Dashboard',
    'PPV Content',
    'payment-ready',
    'PPV content access service',
    ['GET /ppv/contract', 'GET /ppv', 'POST /ppv/content', 'GET /ppv/content/:id', 'POST /ppv/purchase'],
    ['PpvItem', 'PpvPurchase', 'ContentAccessGrant', 'ContentAudit'],
    ['ppv.item_created', 'ppv.unlock_purchased', 'ppv.timed_access_renewed', 'ppv.access_expired'],
    ['age gate', 'content ownership check', 'review approval before purchase', 'timed access expiry enforcement'],
    ['one-off purchase', 'timed unlock renewal', 'buy-to-keep receipt', 'creator revenue split'],
    ['media signing provider', 'refund and takedown path', 'subscription entitlement enforcement'],
    'ppv',
  ),
  [serviceContractKey('Mistress Dashboard', 'E-Store / Vending / Hamper')]: contract(
    'Mistress Dashboard',
    'E-Store / Vending / Hamper',
    'payment-ready',
    'Marketplace order service',
    ['GET /marketplace/orders/seller', 'POST /marketplace/items', 'PATCH /marketplace/orders/:id/status'],
    ['MarketplaceItem', 'MarketplaceOrder', 'FulfilmentEvent', 'InventoryReservation'],
    ['store.item_listed', 'store.order_paid', 'store.fulfilment_updated'],
    ['seller ownership check', 'stock reservation check', 'restricted item review'],
    ['checkout intent', 'seller payout hold', 'shipping or digital receipt'],
    ['provider shipping metadata', 'returns and dispute workflow'],
    'storeSupport',
  ),
  [serviceContractKey('Mistress Dashboard', 'Sales Fulfilment')]: contract(
    'Mistress Dashboard',
    'Sales Fulfilment',
    'payment-ready',
    'Marketplace seller-order service',
    [
      'GET /marketplace/orders/seller?status=&world=&dateFrom=&dateTo=',
      'GET /marketplace/orders/seller/fulfilment-events',
      'GET /marketplace/order/:orderId/timeline',
      'GET /marketplace/order/:orderId/receipt',
      'PATCH /marketplace/order/:orderId/fulfilment',
    ],
    [
      'MarketplaceOrder',
      'MarketplaceFulfilmentEvent',
      'MarketplaceOrderTimelineEvent',
      'MarketplaceOrderReceipt',
      'MarketplaceFulfilmentSlaPolicy',
    ],
    ['store.order_queue_viewed', 'store.fulfilment_updated', 'store.seller_note_added', 'store.receipt_exported'],
    ['seller ownership check', 'HEADMISTRESS/ADMIN cross-seller review', 'paid-order fulfilment gate', 'filtered queue preserves seller scope'],
    ['receipt split', 'seller payout hold', 'refund/cancellation adjustment', 'processor reconciliation estimate'],
    ['automated buyer-flow UI tests', 'live provider shipping/dispute workflow'],
    'marketplaceOrders',
  ),
  [serviceContractKey('Mistress Dashboard', 'Digital Gifts')]: contract(
    'Mistress Dashboard',
    'Digital Gifts',
    'payment-ready',
    'Gift and goal economy service',
    ['GET /gifts/catalogue', 'POST /gifts/send', 'GET /gifts/receipts'],
    ['DigitalGift', 'GiftReceipt', 'GiftOverlayEvent', 'CreatorEarning'],
    ['gift.sent', 'gift.overlay_played', 'gift.receipt_viewed'],
    ['sender balance check', 'recipient visibility check', 'spam and rate limit guard'],
    ['wallet debit', 'gift receipt', 'creator payout split'],
    ['live overlay provider hardening', 'chargeback reversal handling'],
    'giftsGoals',
  ),
  [serviceContractKey('Mistress Dashboard', 'Goals / Wishlist')]: contract(
    'Mistress Dashboard',
    'Goals / Wishlist',
    'payment-ready',
    'Wishlist and contribution service',
    ['GET /wishlist', 'POST /wishlist/reservations', 'PATCH /wishlist/reservations/:id/review'],
    ['WishlistItem', 'WishlistReservation', 'GoalContribution', 'ContributionReceipt'],
    ['wishlist.item_reserved', 'goal.contributed', 'reservation.reviewed'],
    ['admin review for sensitive items', 'contribution visibility consent', 'duplicate reservation prevention'],
    ['goal contribution intent', 'reservation hold', 'creator payout ledger'],
    ['reservation expiry jobs', 'fulfilment evidence upload'],
    'wishlist',
  ),
  [serviceContractKey('Mistress Dashboard', 'Secret Box / Vault Items')]: contract(
    'Mistress Dashboard',
    'Secret Box / Vault Items',
    'policy',
    'Vault access service',
    ['GET /vault-items', 'POST /vault-items', 'POST /vault-items/:id/access-grants'],
    ['VaultItem', 'VaultAccessGrant', 'VaultItemAudit', 'RevocationEvent'],
    ['secret_box.item_created', 'secret_box.access_granted', 'secret_box.access_revoked'],
    ['consent snapshot required', 'revocation path required', 'high-risk item review'],
    ['paid access unlock when enabled', 'refund on revoked unserved access'],
    ['encrypted media storage', 'manual takedown queue'],
    'subVault',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Bank')]: contract(
    'Headmistress Control Centre',
    'Bank',
    'payment-ready',
    'Platform finance service',
    ['GET /admin/economy/bank', 'GET /admin/economy/reserves', 'GET /admin/economy/payout-health', 'GET /admin/economy/provider-readiness'],
    ['PlatformLedgerEntry', 'ReserveBalance', 'PayoutBatch', 'ProviderReadinessSnapshot'],
    ['bank.summary_viewed', 'bank.reserve_reconciled', 'bank.payout_health_checked', 'bank.provider_readiness_checked'],
    ['admin or headmistress role', 'finance audit access', 'signed provider webhook policy'],
    ['provider balance sync', 'reserve allocation', 'payout batch source', 'signed settlement callback'],
    ['deployment-owned provider secrets', 'finance export signing'],
    'headmistressDashboard',
  ),
  [serviceContractKey('Headmistress Control Centre', 'The Books')]: contract(
    'Headmistress Control Centre',
    'The Books',
    'persistence',
    'Ledger and accounting service',
    ['GET /admin/books/ledger', 'GET /admin/books/exports', 'POST /admin/books/reconcile'],
    ['PlatformLedgerEntry', 'LedgerExport', 'ReconciliationRun', 'TaxCategory'],
    ['books.ledger_exported', 'books.reconciliation_started', 'books.adjustment_recorded'],
    ['finance role required', 'immutable adjustment notes', 'export audit trail'],
    ['ledger source receipts', 'refund and payout reconciliation'],
    ['accounting export format approval', 'scheduled reconciliation job'],
    'records',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Cash-In / Cash-Out')]: contract(
    'Headmistress Control Centre',
    'Cash-In / Cash-Out',
    'payment-ready',
    'Top-up and payout service',
    ['GET /admin/economy/top-ups', 'POST /admin/economy/payout-batches', 'POST /money/provider-webhooks/payout-batches/:id/settlement', 'PATCH /admin/economy/payouts/:id/review'],
    ['TopUpIntent', 'CashOutRequest', 'PayoutBatch', 'PayoutReviewAudit', 'ProviderWebhookVerification'],
    ['cashin.topup_reviewed', 'cashout.request_reviewed', 'cashout.batch_created', 'cashout.provider_settlement_signed'],
    ['KYC/KYB readiness', 'payout hold review', 'high-risk cash-out escalation', 'HMAC provider signature required in production'],
    ['payment provider webhook', 'payout provider transfer', 'refund ledger entry', 'provider settlement reconciliation'],
    ['deployment provider approvals', 'payout retry and reversal workflow'],
    'adminEconomy',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Message / Voice / Video Calls')]: contract(
    'Headmistress Control Centre',
    'Message / Voice / Video Calls',
    'policy',
    'Communications safety service',
    ['GET /admin/communications/review-queue', 'PATCH /admin/communications/:id/review', 'GET /admin/communications/audit'],
    ['CommunicationThread', 'CommunicationReview', 'CallSessionAudit', 'SafetyEscalation'],
    ['communication.review_opened', 'communication.action_taken', 'call.session_audited'],
    ['moderation role required', 'private-content minimisation', 'red-flag escalation'],
    ['paid-message receipt review', 'call fee dispute link'],
    ['provider transcript policy decision', 'retention schedule'],
    'adminQueue',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Locked Secret Box')]: contract(
    'Headmistress Control Centre',
    'Locked Secret Box',
    'policy',
    'Locked access governance service',
    ['GET /admin/vault/secret-box/review', 'PATCH /admin/vault/secret-box/:id/review', 'POST /admin/vault/secret-box/:id/revoke'],
    ['VaultItem', 'VaultAccessGrant', 'VaultReviewAudit', 'RevocationEvent'],
    ['secret_box.review_opened', 'secret_box.review_decision', 'secret_box.revoked_by_admin'],
    ['high-risk review queue', 'revocation audit note', 'consent evidence required'],
    ['paid access refund link', 'creator earning reversal when required'],
    ['bulk revocation tool', 'storage provider takedown callback'],
    'subVault',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Key Keeper')]: contract(
    'Headmistress Control Centre',
    'Key Keeper',
    'policy',
    'Agreement governance service',
    ['GET /admin/keeper/agreements', 'PATCH /admin/keeper/agreements/:id/review', 'POST /admin/keeper/agreements/:id/revoke'],
    ['KeeperAgreement', 'AgreementConsentSnapshot', 'AgreementReviewAudit', 'RevocationEvent'],
    ['keeper.review_opened', 'keeper.review_decision', 'keeper.revoked_by_admin'],
    ['consent snapshot required', 'admin note required', 'revocation reason required'],
    ['keeper allowance refund link', 'paid agreement receipt'],
    ['template approval workflow', 'signed export storage'],
    'keeperAllowance',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Goal Contributions')]: contract(
    'Headmistress Control Centre',
    'Goal Contributions',
    'payment-ready',
    'Contribution governance service',
    ['GET /admin/goals/contributions', 'PATCH /admin/goals/contributions/:id/review', 'GET /admin/goals/payout-impact'],
    ['GoalContribution', 'ContributionReceipt', 'ContributionReviewAudit', 'CreatorEarning'],
    ['goal.contribution_reviewed', 'goal.payout_impact_viewed', 'goal.refund_linked'],
    ['high-value contribution review', 'visibility consent', 'refund impact warning'],
    ['contribution intent', 'creator earning ledger', 'refund reversal'],
    ['provider dispute webhook', 'goal fulfilment proof policy'],
    'giftsGoals',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Digital Gifts')]: contract(
    'Headmistress Control Centre',
    'Digital Gifts',
    'payment-ready',
    'Gift governance service',
    ['GET /admin/gifts/receipts', 'PATCH /admin/gifts/:id/review', 'GET /admin/gifts/revenue'],
    ['GiftReceipt', 'DigitalGift', 'GiftReviewAudit', 'CreatorEarning'],
    ['gift.reviewed', 'gift.refund_linked', 'gift.revenue_exported'],
    ['refund review', 'spam review', 'creator visibility consent'],
    ['gift provider receipt', 'creator payout ledger', 'refund reversal'],
    ['live overlay failure handling', 'bulk gift abuse controls'],
    'giftsGoals',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Ad Revenue Share')]: contract(
    'Headmistress Control Centre',
    'Ad Revenue Share',
    'service-contract',
    'Revenue share service',
    ['GET /admin/revenue-share/summary', 'POST /admin/revenue-share/import', 'GET /admin/revenue-share/creator-splits'],
    ['AdRevenueImport', 'RevenueShareLedger', 'CreatorRevenueShare', 'TrafficAttribution'],
    ['ad_revenue.imported', 'ad_revenue.split_calculated', 'ad_revenue.exported'],
    ['admin finance role', 'attribution source approval', 'manual adjustment note'],
    ['creator split ledger', 'payout batch inclusion'],
    ['provider import adapter', 'attribution reconciliation'],
    'adminAnalytics',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Auction')]: contract(
    'Headmistress Control Centre',
    'Auction',
    'service-contract',
    'Auction commerce service',
    ['GET /admin/auctions', 'POST /admin/auctions', 'PATCH /admin/auctions/:id/settle'],
    ['Auction', 'AuctionBid', 'AuctionSettlement', 'MarketplaceOrder'],
    ['auction.created', 'auction.bid_flagged', 'auction.settled'],
    ['bid fraud guard', 'restricted item review', 'winner settlement audit'],
    ['bid hold', 'winner charge', 'seller payout hold'],
    ['real-time bid lock', 'failed settlement recovery'],
    'marketplaceInventory',
  ),
  [serviceContractKey('Headmistress Control Centre', 'E-Store')]: contract(
    'Headmistress Control Centre',
    'E-Store',
    'payment-ready',
    'Marketplace governance service',
    ['GET /admin/marketplace/items', 'PATCH /admin/marketplace/items/:id/review', 'GET /admin/marketplace/orders'],
    ['MarketplaceItem', 'MarketplaceOrder', 'ItemReviewAudit', 'FulfilmentEvent'],
    ['estore.item_reviewed', 'estore.order_reviewed', 'estore.dispute_opened'],
    ['restricted item review', 'seller ownership', 'dispute escalation'],
    ['checkout receipt', 'seller payout hold', 'refund reversal'],
    ['returns workflow', 'shipping provider adapter'],
    'marketplaceInventory',
  ),
  [serviceContractKey('Headmistress Control Centre', 'Compliance & Security')]: contract(
    'Headmistress Control Centre',
    'Compliance & Security',
    'policy',
    'Compliance and audit service',
    ['GET /admin/compliance/risk-rollup', 'GET /admin/compliance/audit-events', 'GET /admin/compliance/audit-events/export.csv', 'GET /admin/compliance/retention-export-controls', 'PATCH /admin/compliance/cases/:id'],
    ['ComplianceCase', 'PolicyGuardSnapshot', 'AuditEvent', 'RetentionExportControl', 'IdentityVerification'],
    ['compliance.case_opened', 'compliance.policy_decision', 'compliance.audit_exported', 'compliance.retention_policy_checked'],
    ['admin/headmistress access only', 'identity/consent evidence required', 'immutable audit trail'],
    ['payment dispute link', 'refund or payout hold trigger'],
    ['provider identity verification', 'tamper-proof storage attestation'],
    'adminQueue',
  ),
};

const fallbackContract = (roleSurface: string, title: string): DashboardModuleServiceContract => ({
  id: serviceContractKey(roleSurface, title),
  title,
  stage: 'scaffold',
  serviceOwner: `${roleSurface} module service`,
  apiSurface: ['Define list endpoint', 'Define detail endpoint', 'Define review/action endpoint'],
  persistence: ['Module record', 'Module audit event', 'Module settings'],
  auditEvents: ['module.opened', 'module.action_requested', 'module.reviewed'],
  policyGates: ['role access', 'owner visibility', 'audit note on sensitive actions'],
  paymentHooks: ['attach receipt only if the module charges money'],
  launchBlockers: ['confirm backend owner', 'add persistence migration', 'add focused service tests'],
});

export function getDashboardModuleServiceContract(roleSurface: string, title: string) {
  return dashboardModuleServiceContracts[serviceContractKey(roleSurface, title)] || fallbackContract(roleSurface, title);
}

export function dashboardModuleContractStageLabel(stage: DashboardModuleContractStage) {
  if (stage === 'service-contract') return 'Service Contract';
  if (stage === 'payment-ready') return 'Payment Ready';
  if (stage === 'production-ready') return 'Production Ready';
  if (stage === 'persistence') return 'Persistence Mapped';
  if (stage === 'policy') return 'Policy Guarded';
  return 'Scaffold';
}
