import type {
  MXExportFormat,
  MXImportFormat,
  MXMagneticAdapterCapability,
  MXMagneticAdapterRegistryEntry,
  MXTargetRuntime,
} from './mxMagneticAdapterTypes';

export const MX_MAGNETIC_IMPORT_FORMATS: MXImportFormat[] = [
  'svg-image',
  'svg-font',
  'ico',
  'woff',
  'woff2',
  'ttf',
  'otf',
  'json-manifest',
  'style-guide',
];

export const MX_MAGNETIC_EXPORT_FORMATS: MXExportFormat[] = [
  'svg-image',
  'svg-sprite',
  'symbol-defs',
  'icon-font',
  'web-component',
  'react-component',
  'react-native-component',
  'vue-component',
  'elm-component',
  'flutter-reference',
  'png-24',
  'indexed-png',
  'favicon-ico',
  'photoshop-csh',
  'tailwind-token-file',
  'css-variable-file',
  'marketplace-pack-card',
  'expanded-info-card',
  'download-bundle',
];

export const MX_MAGNETIC_TARGET_RUNTIMES: MXTargetRuntime[] = [
  'vite',
  'rollup',
  'webpack',
  'esbuild',
  'rspack',
  'react-web',
  'react-native',
  'expo',
  'vue',
  'web-component',
  'tailwind-css',
  'plain-svg',
];

export const MX_MAGNETIC_CAPABILITIES: MXMagneticAdapterCapability[] = [
  'on-demand-icons',
  'auto-import-registry',
  'component-registry',
  'svg-sprite-build',
  'svgo-cleanup',
  'css-token-export',
  'tailwind-token-export',
  'marketplace-front-card',
  'marketplace-expanded-card',
  'download-bundle-manifest',
  'web-component-output',
  'react-output',
  'react-native-output',
  'vue-output',
  'raster-preview-output',
];

export const MX_MAGNETIC_ADAPTER_REGISTRY: MXMagneticAdapterRegistryEntry[] = [
  {
    id: 'mx-icons-on-demand-adapter',
    name: 'MX Icons On-Demand Adapter',
    summary: 'Turns generated Mistress-X icons into semantic, on-demand icon component outputs inspired by unplugin-icons style workflows.',
    family: 'icons',
    tier: 'generated',
    inputFormats: ['svg-image', 'svg-font', 'json-manifest', 'style-guide'],
    outputFormats: ['svg-image', 'svg-sprite', 'symbol-defs', 'web-component', 'react-component', 'react-native-component', 'vue-component', 'tailwind-token-file', 'marketplace-pack-card', 'expanded-info-card'],
    targetRuntimes: ['vite', 'rollup', 'webpack', 'esbuild', 'rspack', 'react-web', 'react-native', 'expo', 'vue', 'web-component', 'tailwind-css', 'plain-svg'],
    capabilities: ['on-demand-icons', 'component-registry', 'svg-sprite-build', 'svgo-cleanup', 'web-component-output', 'react-output', 'react-native-output', 'vue-output', 'tailwind-token-export', 'marketplace-front-card', 'marketplace-expanded-card'],
    generatedBy: 'mistress-x-styling-engine',
    magneticVersion: '0.1.0',
    supportsAutoImport: true,
    supportsOnDemandIcons: true,
    supportsTailwindTokens: true,
    supportsSvgoCleanup: true,
    supportsMarketplaceCard: true,
    supportsExpandedInfoCard: true,
    status: 'scaffolded',
    progress: 72,
    nextStep: 'Generate icon manifest metadata and route it into the pack export bundle.',
  },
  {
    id: 'mx-auto-import-registry-adapter',
    name: 'MX Auto Import Registry Adapter',
    summary: 'Prepares generated asset components and helper hooks for auto-import style registries across web and app builds.',
    family: 'ui-components',
    tier: 'generated',
    inputFormats: ['json-manifest', 'style-guide'],
    outputFormats: ['react-component', 'react-native-component', 'vue-component', 'tailwind-token-file', 'css-variable-file', 'download-bundle'],
    targetRuntimes: ['vite', 'rollup', 'webpack', 'esbuild', 'rspack', 'react-web', 'react-native', 'expo', 'vue'],
    capabilities: ['auto-import-registry', 'component-registry', 'react-output', 'react-native-output', 'vue-output', 'tailwind-token-export', 'css-token-export', 'download-bundle-manifest'],
    generatedBy: 'mistress-x-styling-engine',
    magneticVersion: '0.1.0',
    supportsAutoImport: true,
    supportsOnDemandIcons: false,
    supportsTailwindTokens: true,
    supportsSvgoCleanup: false,
    supportsMarketplaceCard: false,
    supportsExpandedInfoCard: false,
    status: 'scaffolded',
    progress: 66,
    nextStep: 'Add generated auto import map to the export bundle metadata.',
  },
  {
    id: 'mx-css-tailwind-token-adapter',
    name: 'MX CSS + Tailwind Token Adapter',
    summary: 'Converts Mistress-X style guides into CSS variables, Tailwind-safe tokens, glow utilities and reusable theme metadata.',
    family: 'themes',
    tier: 'generated',
    inputFormats: ['style-guide', 'json-manifest'],
    outputFormats: ['css-variable-file', 'tailwind-token-file', 'react-component', 'png-24', 'marketplace-pack-card', 'expanded-info-card'],
    targetRuntimes: ['vite', 'rollup', 'webpack', 'esbuild', 'rspack', 'react-web', 'react-native', 'expo', 'tailwind-css'],
    capabilities: ['css-token-export', 'tailwind-token-export', 'raster-preview-output', 'marketplace-front-card', 'marketplace-expanded-card', 'react-output', 'react-native-output'],
    generatedBy: 'mistress-x-styling-engine',
    magneticVersion: '0.1.0',
    supportsAutoImport: true,
    supportsOnDemandIcons: false,
    supportsTailwindTokens: true,
    supportsSvgoCleanup: false,
    supportsMarketplaceCard: true,
    supportsExpandedInfoCard: true,
    status: 'wired',
    progress: 78,
    nextStep: 'Wire generated token files into real app theme packs.',
  },
  {
    id: 'mx-marketplace-card-adapter',
    name: 'MX Marketplace Card Adapter',
    summary: 'Generates the front-facing little box/menu-card preview and expanded product sheet for each pack or bundle.',
    family: 'themes',
    tier: 'generated',
    inputFormats: ['json-manifest', 'style-guide', 'svg-image'],
    outputFormats: ['marketplace-pack-card', 'expanded-info-card', 'png-24', 'indexed-png', 'download-bundle'],
    targetRuntimes: ['react-web', 'react-native', 'expo', 'plain-svg'],
    capabilities: ['marketplace-front-card', 'marketplace-expanded-card', 'raster-preview-output', 'download-bundle-manifest'],
    generatedBy: 'mistress-x-styling-engine',
    magneticVersion: '0.1.0',
    supportsAutoImport: false,
    supportsOnDemandIcons: false,
    supportsTailwindTokens: true,
    supportsSvgoCleanup: true,
    supportsMarketplaceCard: true,
    supportsExpandedInfoCard: true,
    status: 'wired',
    progress: 82,
    nextStep: 'Connect generated front/expanded card drafts to downloadable bundle export paths.',
  },
  {
    id: 'mx-font-icon-export-adapter',
    name: 'MX Font + Icon Export Adapter',
    summary: 'Captures IcoMoon-style font and icon output coverage for SVG fonts, WOFF, WOFF2, TTF, OTF, favicon, PNG and Photoshop shape outputs.',
    family: 'fonts',
    tier: 'generated',
    inputFormats: ['svg-font', 'svg-image', 'ico', 'woff', 'woff2', 'ttf', 'otf'],
    outputFormats: ['icon-font', 'svg-image', 'svg-sprite', 'favicon-ico', 'png-24', 'indexed-png', 'photoshop-csh', 'download-bundle'],
    targetRuntimes: ['plain-svg', 'react-web', 'web-component', 'vite', 'rollup', 'webpack'],
    capabilities: ['svg-sprite-build', 'svgo-cleanup', 'raster-preview-output', 'download-bundle-manifest'],
    generatedBy: 'mistress-x-styling-engine',
    magneticVersion: '0.1.0',
    supportsAutoImport: false,
    supportsOnDemandIcons: false,
    supportsTailwindTokens: false,
    supportsSvgoCleanup: true,
    supportsMarketplaceCard: true,
    supportsExpandedInfoCard: true,
    status: 'planned',
    progress: 52,
    nextStep: 'Add real export file writers for font and favicon bundles.',
  },
];

export function getMagneticAdapterById(id: string) {
  return MX_MAGNETIC_ADAPTER_REGISTRY.find((adapter) => adapter.id === id);
}

export function getMagneticAdaptersByRuntime(runtime: MXTargetRuntime) {
  return MX_MAGNETIC_ADAPTER_REGISTRY.filter((adapter) => adapter.targetRuntimes.includes(runtime));
}

export function getMagneticAdaptersByCapability(capability: MXMagneticAdapterCapability) {
  return MX_MAGNETIC_ADAPTER_REGISTRY.filter((adapter) => adapter.capabilities.includes(capability));
}

export function getMagneticAdapterProgress() {
  const total = MX_MAGNETIC_ADAPTER_REGISTRY.reduce((sum, adapter) => sum + adapter.progress, 0);
  return Math.round(total / MX_MAGNETIC_ADAPTER_REGISTRY.length);
}
