import type { DigitalGiftAsset, DigitalGiftStoreSummary, DigitalGiftUploadDraft } from './digitalGiftTypes';

export const starterDigitalGiftAssets: DigitalGiftAsset[] = [
  {
    id: 'velvet-bow-gift',
    name: 'Velvet Bow Gift',
    kind: 'single-gift',
    rarity: 'common',
    status: 'listed',
    accessRule: 'public-store',
    priceCredits: 10,
    stockLimit: 250,
    soldCount: 48,
    tags: ['bow', 'soft', 'gift'],
    previewLabel: '🎀',
    description: 'A soft digital bow gift for quick appreciation, rewards, and entry-level gifting.',
  },
  {
    id: 'luxury-locks-set',
    name: 'Luxury Locks Set',
    kind: 'bundle',
    rarity: 'premium',
    status: 'ready-to-upload',
    accessRule: 'vip-only',
    priceCredits: 129,
    stockLimit: 100,
    soldCount: 0,
    tags: ['luxury', 'locks', 'bundle'],
    previewLabel: '🔒',
    description: 'Upload-ready lock-themed gift bundle generated from the Gift Bundle Builder workflow.',
    bundleManifestId: 'luxury-locks-set',
    uploadFileName: 'luxury-locks-set.bundle.json',
  },
  {
    id: 'gold-ui-essentials',
    name: 'Gold UI Essentials',
    kind: 'seasonal-pack',
    rarity: 'limited',
    status: 'draft',
    accessRule: 'creator-only-preview',
    priceCredits: 99,
    stockLimit: 75,
    soldCount: 0,
    tags: ['gold', 'ui', 'starter-pack'],
    previewLabel: '✨',
    description: 'A polished gold utility pack prepared for creator review before store listing.',
    bundleManifestId: 'gold-ui-essentials',
    uploadFileName: 'gold-ui-essentials.bundle.json',
  },
  {
    id: 'christmas-icon-pack',
    name: 'Christmas Icon Pack',
    kind: 'seasonal-pack',
    rarity: 'limited',
    status: 'paused',
    accessRule: 'subscribers-only',
    priceCredits: 79,
    stockLimit: 300,
    soldCount: 0,
    tags: ['christmas', 'holiday', 'limited'],
    previewLabel: '🎄',
    description: 'A seasonal digital gift pack for Christmas drops and holiday collector campaigns.',
    bundleManifestId: 'christmas-icon-pack',
    uploadFileName: 'christmas-icon-pack.bundle.json',
  },
];

export const starterDigitalGiftUploadDraft: DigitalGiftUploadDraft = {
  id: 'gift-upload-draft-001',
  title: 'Luxury Locks Set',
  subtitle: 'Premium lock-themed bundle ready for VIP store upload.',
  description: 'Use the bundle manifest from the Gift Bundle Builder and prepare this digital gift for pricing, access, stock limits, and store preview.',
  kind: 'bundle',
  rarity: 'premium',
  accessRule: 'vip-only',
  priceCredits: 129,
  tags: ['luxury', 'locks', 'vip', 'bundle'],
  sourceManifest: 'luxury-locks-set.bundle.json',
  uploadChecklist: [
    { id: 'manifest', label: 'Manifest attached', complete: true },
    { id: 'preview-card', label: 'Store card preview checked', complete: true },
    { id: 'pricing', label: 'Pricing and rarity selected', complete: true },
    { id: 'access', label: 'Access rule selected', complete: true },
    { id: 'stock', label: 'Stock limit reviewed', complete: false },
  ],
};

export function buildDigitalGiftStoreSummary(assets: DigitalGiftAsset[]): DigitalGiftStoreSummary {
  return {
    totalAssets: assets.length,
    listedAssets: assets.filter((asset) => asset.status === 'listed').length,
    draftAssets: assets.filter((asset) => asset.status === 'draft').length,
    readyToUploadAssets: assets.filter((asset) => asset.status === 'ready-to-upload').length,
    soldOutAssets: assets.filter((asset) => asset.status === 'sold-out').length,
    totalStockLimit: assets.reduce((sum, asset) => sum + Number(asset.stockLimit || 0), 0),
    totalSoldCount: assets.reduce((sum, asset) => sum + Number(asset.soldCount || 0), 0),
  };
}
